project:
  type: website
  output-dir : docs

website:
  title: "projects/four-parameters-categorical"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



